### ISSUE TITLE
Screenshots or video?

### ISSUE THREAD

**Issue by patricklynch** [rparet/darkpawns#6]
I played this game as a kid and I am dying to see a gameplay video. Does anyone have anything?! I have scoured the internet and found little more than a sample ASCII map. Anyway, at least the code is fun to browse. Thanks for publishing this 👍 .

**Comment by TromboneSteve** [comment]
> I played this game as a kid and I am dying to see a gameplay video. Does anyone have anything?! I have scoured the internet and found little more than a sample ASCII map. Anyway, at least the code is fun to browse. Thanks for publishing this 👍 .

I may have some stuff. No screen recordings, though. I still have all of my folders from back then. It'll take me about a day to see what I have. I was Sparx btw

**Comment by patricklynch** [comment]
Ok, no rush. Thanks!
